-- add hint at status bar
--vim.api.nvim_create_autocmd("VimEnter", {
--  callback = function()
--    vim.defer_fn(function()
--      vim.cmd [[
--        echohl ModeMsg |
--        echom "Hint: s + letter → Flash jump | <leader>fk → Telescope keymaps" |
--        echohl None
--      ]]
--    end, 500)
--  end,
--})
